name: Use Secrets

# Trigger the workflow on push events
on: [push]

jobs:
  build:

    # Specify the environment where the job will run
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        # Use the aws-actions/configure-aws-credentials action to set up AWS credentials
        # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          # Use secrets to store sensitive information
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          # Create a secret named AWS_REGION to store the region value
          aws-region: us-west-2

      - name: Get caller identity
        # Run a command to get the details for the account in use
        run: aws sts get-caller-identity

      - name: List S3 Buckets
        # Run a command to list all S3 buckets
        run: aws s3api list-buckets
